"""
aimmd.pathensemble._reweight
===========================

Reweighting of path-sampling ensembles.

This module defines :class:`PathEnsembleReweight`, a mixin that implements a
single high-level operation:

- :meth:`PathEnsembleReweight.reweight` assigns statistical weights to the paths
  in a :class:`aimmd.pathensemble.PathEnsemble` such that the resulting weighted
  ensemble can be used to estimate free energies and (in a coarse form) rates.

The implementation is tailored to the AIMMD path type convention used by the
trainer. It assumes that each stored path carries a compact categorical label
(``path.type``) encoding:

- the state the path started from,
- whether it enters the reactive region,
- the state it ends in,
- and whether it was generated as a "free" excursion or as a shot trajectory.

The mixin does not change any path data. It produces a per-path weight vector
and several diagnostic arrays that are useful for analysis and debugging.

High-level algorithm
--------------------
Reweighting proceeds in three stages.

1) Split paths into two groups using ``path.type``:
   - excursion paths (start outside r, enter r),
   - internal paths (start in r and go back to the initial state).
   Internal paths are used only to normalize the excursion weights.

2) For excursions, define a per-path correction factor that compensates for
   non-uniform shooting density at the shooting point.
   This is computed from the local density of the `source` values around the
   shooting value (see :func:`compute_shooting_density`) and then optionally
   "uniformized" across the ensemble (see :func:`uniformize_factors`).

3) Compute crossing probabilities as a function of extreme values along the
   path and reweight excursions with :func:`reweight_excursions`.
   The result is a weight per excursion, which is inserted into the global
   `weights` array at the correct absolute indices.
   Internal paths are assigned weights that normalize the total weight.

Direction convention
--------------------
The reweighting is directional: it estimates weights for excursions linked to a
chosen initial state `s` and final state `o` through a reactive region `r`.

The `states` argument is interpreted as:

- `states = 'SRO'` (default style: 3 characters)
    `s` : initial state label
    `r` : reactive region label
    `o` : final state label
    If `states = 'ARB'` (default), then `s = 'A'`, etc.

- `states` shorter than 3 characters
    Only `r` is used; `s` and `o` are set to the empty string.
    In this mode, the method returns only factors/diagnostics (see below).

To treat "the opposite direction" (e.g. compute weights for o→s), call
:meth:`reweight` with ``states[::-1]``. The trainer does this explicitly.

Forward/backward portions and extremes
--------------------------------------
The reweighting uses the *extreme* value reached along a path as a proxy for
how far it penetrates the reactive region. The extreme is computed on internal
values only (excluding boundary frames when appropriate), and its definition is
direction-dependent:

- if `s < o`  : extreme is ``+nanmax(values)``
- if `s > o`  : extreme is ``-nanmin(values)``

This sign convention makes the "more advanced" direction correspond to larger
extreme values even when sampling in the opposite direction. This setting
assumes that the values function is a reaction coordinate that always orders
states from A to B, and never from B to A. This is indeed how AIMMD trains
the network.

The method also constructs "partial extremes" (stored in `xP_extremes`) for
the backward and forward portions of shot trajectories, where:

- backward portion: up to the shooting point (included),
- forward portion : starting from the shooting point (included),

using the internalized value array and an adjusted shooting index.

This is used by :func:`compute_crossing_probability`.

Free excursions and shot excursions
-----------------------------------
Excursions are classified as:

- free excursions
  Trajectories that were not generated by a shooting move in the reactive
  region. For these, shooting values are set to ±inf and factors are left as 1
  (possibly modified by `sp_cutoff_min/max`).

- shot excursions
  Trajectories generated by shooting. For these, factors are computed from the
  local shooting density and optionally uniformized.

`sp_cutoff_min` and `sp_cutoff_max` allow reclassifying shots whose shooting
value lies outside a specified interval as "free", and applying a special factor
based on how many internal frames lie below/above the cutoff. This is a
practical mechanism for stabilizing reweighting when shots occur in regions
where density estimation is unreliable.

Return value
------------
:meth:`reweight` returns a tuple of arrays. The most important element is
the first one, `weights`, which is a vector of length ``len(self)`` aligned with
the ensemble order.

The additional arrays are diagnostics and intermediate quantities that are used
by the trainer (and are useful for plotting and debugging).

Example
-------
The trainer uses reweighting in both directions and combines the resulting
weights to populate the ensemble weights, restricted to excursions:

    # reweight
    result1 = pathensemble.reweight(states, **rw_p, source=source)
    result2 = pathensemble.reweight(states[::-1], **rw_p, source=source)
    w1, extremes1, xP1 = result1[0], result1[4], result1[5]
    w2, extremes2, xP2 = result2[0], result2[4], result2[5]

    # assign weights only to excursions
    excursions_mask = pathensemble.types(f'.{r}..')
    pathensemble.weights = (w1 + w2) * excursions_mask

    # bonus track: estimate rates
    lengths = pathensemble.n_frames
    k12 = np.sum(w1 * lengths)
    k12 = 1 / k12 if k12 else nan
    k21 = np.sum(w2 * lengths)
    k21 = 1 / k21 if k21 else nan
    print(f'    k12 estimate: {k12:.3e} [1/dt]')
    print(f'    k21 estimate: {k21:.3e} [1/dt]')

Notes
-----
- The "rate" estimates above are the simple reciprocal-of-mean first-passage
  time estimator under the reweighted measure, expressed in units of 1/dt where
  dt is the per-frame time step. The code computes this as ``1 / Σ(w * length)``.
- This module is a thin orchestrator. The statistical core is implemented in
  :mod:`aimmd.pathensemble.reweight` (imported functions below).
"""

# external
import numpy as np
from abc import ABC
from math import inf, nan

# aimmd imports
from .reweight import compute_shooting_density
from .reweight import uniformize_factors
from .reweight import compute_crossing_probability
from .reweight import reweight_excursions

class PathEnsembleReweight(ABC):
    
    def reweight(
        self,
        states='ARB',
        free_threshold=50,
        theoretical_threshold=None,
        crossing_probability_cutoff=0.,
        factors_neighbors=10,
        factors_norm=10,
        factors_cutoff=1.,
        sp_cutoff_min=None,
        sp_cutoff_max=None,
        source='values'):
        """
        Reweight an ensemble of paths.

        Parameters
        ----------
        states : str, default='ARB'
            State specification. Interpreted as a string and converted to upper
            case. If at least three characters are provided, the first three are
            used as:
                s = states[0]  (initial state)
                r = states[1]  (reactive region)
                o = states[2]  (final state)
            If fewer than three characters are provided, only `r` is used and
            `s` and `o` are set to the empty string. In that mode, the method
            returns diagnostic factors without performing directional reweighting
            (see "Just factors" return below).

        free_threshold : float, default=50
            Threshold (in the extreme-value coordinate) used by
            :func:`compute_crossing_probability` to decide which events are
            treated as "free" crossings when estimating crossing probabilities.

        theoretical_threshold : float, optional
            Optional theoretical threshold forwarded to
            :func:`compute_crossing_probability`. If provided, it is used as an
            additional constraint on the crossing model.

        crossing_probability_cutoff : float, default=0.
            Lower cutoff forwarded to :func:`compute_crossing_probability`.
            Crossing probabilities below this cutoff are suppressed.

        factors_neighbors : int, default=10
            Neighborhood size used by :func:`compute_shooting_density` when
            estimating the local density at the shooting value.

        factors_norm : int, default=10
            If non-zero, enable factor uniformization among shot excursions
            using :func:`uniformize_factors`. The value is passed as the
            `norm` argument to that function.

        factors_cutoff : float, default=1.
            Cutoff parameter forwarded to :func:`uniformize_factors`.

        sp_cutoff_min, sp_cutoff_max : float, optional
            Optional shooting-value cutoffs used to reclassify some shot paths
            as free. Shots with shooting values outside the interval
            [sp_cutoff_min, sp_cutoff_max] are treated as free excursions with
            special factors based on the count of internal frames beyond the
            cutoff.

        source : str, default='values'
            Per-frame stream used by Path extractors. This is passed to Path
            methods such as ``shooting(source)``, ``internal(source)``, and
            attribute access via ``getattr(path, source)``. In typical usage,
            this is `'values'` (the CV used for sampling), but it can be any
            Path-supported stream.

        Returns
        -------
        tuple
            If `s != o` (directional reweighting mode), returns:

            weights : numpy.ndarray, shape (len(self),)
                Per-path weights aligned with the ensemble order.

            indices : numpy.ndarray
                Absolute indices of the excursion paths that were actually
                reweighted (linked to `s` via start or end), ordered according
                to the internal `order` returned by :func:`reweight_excursions`.

            factors : numpy.ndarray, shape (n_excursions,)
                Per-excursion correction factors (1 for free excursions, density
                corrected for shot excursions, and possibly uniformized).

            shooting_values : numpy.ndarray, shape (n_excursions,)
                Per-excursion shooting values in the signed convention used by
                the current direction. Free excursions have their shooting value
                set to ±inf to separate them from shot trajectories.

            extremes : numpy.ndarray, shape (n_excursions,)
                Per-excursion extreme values (signed by direction). For some
                free cases and certain transitions, extremes are set to +inf.

            xP : numpy.ndarray
                Crossing probabilities associated with the extremes, as returned
                by :func:`compute_crossing_probability` / :func:`reweight_excursions`.

            f, m : numpy.ndarray
                Additional diagnostic arrays returned by :func:`reweight_excursions`
                (kept as-is; used for debugging/analysis).

            If `s == o` (diagnostic-only mode), returns:

                (weights, arange(len(self)), factors, shooting_values,
                 extremes, zeros_like(extremes), factors, zeros_like(extremes))

            where `weights` is all zeros and the remaining arrays describe the
            factor/extreme preprocessing performed on excursions.

        Notes
        -----
        Internal paths:
        - Internal segments (paths starting in `r` and going back to `s`) are
          assigned a uniform weight by default.
        - If an internal segment was "shot" (type marker indicates not `r`),
          its weight is scaled by ``1 / n_frames`` and then renormalized.
        - Internal weights are normalized to sum to the excursion total weight
          (or 1 if excursion weights are all zero), and then inserted into the
          global `weights` vector.

        Transition shot excursions:
        - Shot transition paths (from `o` to `s`) are divided by 2 to avoid
          double counting.
        - Factors are clipped to [1e-3, 1000] to avoid extreme weights.
        """

        # process states
        # s: initial state
        # r: reactive region
        # o: final state
        states = str(states).strip().upper()
        if len(states) < 3:
            r = states[0]
            s = o = ''
        else:
            s, r, o = states[:3]
        
        # initialize weights
        weights = np.zeros(len(self))
        
        # get functions
        if s < o:
            extreme_function = lambda x: + np.nanmax(x)
        else:
            extreme_function = lambda x: - np.nanmin(x)
        
        # get types
        types = self.types().view('U1').reshape(len(self), 4)
        
        # absolute indices
        excursion_indices = np.flatnonzero((types[:, 0] != r) &
                                           (types[:, 0] != '.') &
                                           (types[:, 1] == r))
        internal_indices = np.flatnonzero((types[:, 0] == r) &
                                          (types[:, 1] == s))
        
        # reweight excursions
        excursions = self[excursion_indices]
        
        # within excursions indices
        states = types[excursion_indices]
        free = states[:, 3] == s
        shot = states[:, 3] == r
        from_s = states[:, 0] == s
        from_o = states[:, 0] == o
        to_s = states[:, 2] == s
        to_o = states[:, 2] == o
        
        # all (for now)
        factors = np.ones(len(excursion_indices))
        extremes = np.zeros(len(excursion_indices))  # all for now
        shooting_values = excursions.shooting(source)
                
        # shot before sp_cutoff_min -> free
        if sp_cutoff_min is not None:
            mask = shot & (shooting_values < sp_cutoff_min)
            mask = np.flatnonzero(mask)
            f_mask = []
            for i, k in enumerate(mask):
                values = excursions._paths[k].internal(source)
                f_mask.append(1.0 / np.count_nonzero(values < sp_cutoff_min))
                if to_o[i]:
                    extremes[i] = +inf
                else:
                    extremes[i] = extreme_function(values)
            if len(mask):
                factors[mask] = f_mask
                factors[mask] /= np.mean(factors[mask])
                free[mask] = True
                shot[mask] = False
        
        # shot after sp_cutoff_max -> free
        if sp_cutoff_max is not None:
            mask = shot & (shooting_values > sp_cutoff_max)
            mask = np.flatnonzero(mask)
            f_mask = []
            for i, k in enumerate(mask):
                values = excursions._paths[k].internal(source)
                f_mask.append(1.0 / np.count_nonzero(values > sp_cutoff_max))
                if to_o[i]:
                    extremes[i] = +inf
                else:
                    extremes[i] = extreme_function(values)
            if len(mask):
                factors[mask] = f_mask
                factors[mask] /= np.mean(factors[mask])
                free[mask] = True
                shot[mask] = False

        # invert direction of shooting values
        if s > o:  # going in opposite direction
            shooting_values *= -1.0
        
        # free excursions' shooting values and extremes (only from s)
        mask = free & ~to_o
        mask_extremes = []
        for path in excursions.paths[mask]:
            values = path.internal(source)
            mask_extremes.append(extreme_function(values))
        shooting_values[mask] = -inf
        extremes[mask] = mask_extremes
        extremes[free & to_o] = +inf
        
        # free excursions' shooting values and extremes (only from o)
        free_from_o = from_o & to_s & (states[:, 3] == o)
        shooting_values[free_from_o] = +inf
        extremes[free_from_o] = +inf
        
        # we are only left with shot paths (split in forw/back)
        xP_extremes = []
        xP_shooting_values = []
        for i in np.flatnonzero(shot):
            path = excursions._paths[i]
            shooting_value = shooting_values[i]
            values = getattr(path, source)
                        
            factors[i] = 1.0 / compute_shooting_density(
                values, shooting_value, factors_neighbors)
            if not (to_s[i] or from_s[i]):
                continue
            if to_s[i] or to_o[i]:
                values = values[1:-1]
            else:  # for sure it must start in a state
                values = values[1:]
            shooting_index = path.shooting_index - 1
            # backward part
            if to_s[i]:
                if from_o[i]:
                    xP_extremes.append(+inf)
                    extremes[i] = +inf  # a transition
                else:  # an excursion
                    # no "+1" because already internal values
                    v = values[:shooting_index + 1]
                    xP_extremes.append(extreme_function(v))
                    extremes[i] = extreme_function(values)
                xP_shooting_values.append(shooting_value)
            # forward part
            if from_s[i]:
                if to_o[i]:
                    xP_extremes.append(+inf)
                    extremes[i] = +inf  # a transition
                else:
                    v = values[shooting_index:]
                    xP_extremes.append(extreme_function(v))
                    extremes[i] = extreme_function(values)
                xP_shooting_values.append(shooting_value)
        
        # uniformize factors among shot excursions
        if factors_norm:
            mask = shot * (factors > 0)
            factors[mask] = uniformize_factors(
                factors[mask], shooting_values[mask],
                factors_cutoff, factors_norm)
        
        # final processing
        shot_transitions = shot & to_s & from_o
        factors[shot_transitions] /= 2  # we need to downweight transitions
        # by a factor 2, otherwise we count them double
        # that is because we assign an ARB transition to both
        # ARB and BRA reweighting (the latter with inverted velocities)
        mask = factors > 0
        # avoid too many imbalances by clipping the factor
        factors[mask] = np.clip(factors[mask], 1e-3, 1000.)
        
        # just factors
        if s == o:
            return (weights, np.arange(len(self)),
                    factors, shooting_values, extremes,
                    extremes * 0, factors, extremes * 0)

        
        # compute crossing probability
        # for each extreme value: the crossing probability
        xP_extremes, xP = compute_crossing_probability(
            xP_shooting_values,
            xP_extremes,
            extremes[free],
            factors[free],
            free_threshold,
            theoretical_threshold,
            crossing_probability_cutoff)
        
        # reweight excursions linked to state s
        excursions_mask = from_s | to_s
        w, order, shooting_values, extremes, xP, f, m = reweight_excursions(
            shooting_values[excursions_mask],
            extremes[excursions_mask],
            factors[excursions_mask],
            xP_extremes, xP)
        weights[excursion_indices[excursions_mask]] = w
        
        # reweight internal segments: by default, all the same weight
        internal_weights = np.ones(len(internal_indices))

        # special treatment: internal segments which were shot
        int_shot = types[internal_indices, 3] != r
        if int_shot.any():  # if shot in init state, special treatment!
            internal_weights[int_shot] = (
                1 / self[internal_indices[int_shot]].n_frames)
            internal_weights[int_shot] /= internal_weights[int_shot].mean()
        
        # normalization
        norm = internal_weights.sum()
        if norm:
            internal_weights /= norm
            internal_weights *= weights.sum() or 1.
        weights[internal_indices] = internal_weights
        
        # return
        return (weights, excursion_indices[excursions_mask][order],
                factors, shooting_values, extremes, xP, f, m)
    
    def factors(self, neighbors=10, norm=10, cutoff=1.,
                sp_cutoff_min=None, sp_cutoff_max=None):
        """
        Convenience wrapper for reweighting factors.

        This method calls :meth:`reweight` in diagnostic-only mode (``states=''``)
        and returns its first element.

        Parameters
        ----------
        neighbors : int, default=10
            Passed as ``factors_neighbors`` to :meth:`reweight`.
        norm : int, default=10
            Passed as ``factors_norm`` to :meth:`reweight`.
        cutoff : float, default=1.
            Passed as ``factors_cutoff`` to :meth:`reweight`.
        sp_cutoff_min, sp_cutoff_max : float, optional
            Passed through to :meth:`reweight`.

        Returns
        -------
        numpy.ndarray
            First element returned by :meth:`reweight` (kept as-is).

        Notes
        -----
        In diagnostic-only mode, :meth:`reweight` returns several arrays
        (factors, shooting values, extremes, ...). This wrapper exposes only
        the first return element to preserve historical behavior.
        """
        return self.reweight('',
                             factors_neighbors=neighbors,
                             factors_norm=norm,
                             factors_cutoff=cutoff,
                             sp_cutoff_min=sp_cutoff_min,
                             sp_cutoff_max=sp_cutoff_max)[0]
